galaxy_info:
  author: whatot whatot2@gmail.com
  description: config Archlinux and Manjaro
  company: None

  license: BSD

  min_ansible_version: 1.2

  platforms:
    - name: Archlinux
      versions:
        - all

  galaxy_tags: []

dependencies: []
