# only want all in one file, not Best Pratice
- hosts: localhost

  tasks:
  - name: Config archlinuxcn in pacman.conf
    blockinfile:
      dest: /etc/pacman.conf
      block: |
        [archlinuxcn]
        SigLevel = Optional TrustedOnly
        Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch

  - debug: var=ansible_distribution

  - name: Using ustc mirror in /etc/pacman.d/mirrorlist in Archlinux
    shell: sed -i '/ustc/s/^#//' /etc/pacman.d/mirrorlist
    when: ansible_distribution == "Archlinux"

  - name: Setup /etc/pacman-mirrors.conf in Manjaro
    lineinfile:
      regexp: '^OnlyCountry = China$'
      line: 'OnlyCountry = China'
      dest: /etc/pacman-mirrors.conf
      state: present
      insertafter: EOF
    when: ansible_distribution == "Manjaro Linux"
    register: pacman_mirrors_conf_updated

  - name: Update /etc/pacman.d/mirrorlist by pacman-mirrors in Manjaro
    shell: pacman-mirrors
    when: ansible_distribution == "Manjaro Linux" and
          (pacman_mirrors_conf_updated | changed)

  - name: Update and Upgrade the system
    pacman: update_cache=yes upgrade=yes

  - name: Set the Asia/Shanghai timezone
    file:
      src: "/usr/share/zoneinfo/Asia/Shanghai"
      dest: /etc/localtime
      state: link
      force: yes

  - name: Install basic packages
    pacman: name={{ item }} state=latest
    with_items:
      - archlinux-keyring
      - archlinuxcn-keyring
      - baka-mplayer
      - calibre
      - clipit
      - deadbeef
      - dnsmasq
      - fcitx
      - fcitx-configtool
      - fcitx-im
      - fcitx-rime
      - file-roller
      - firefox
      - gedit
      - git
      - gnome-clocks
      - gnome-tweak-tool
      - google-chrome
      - gvim
      - libvirt
      - mpv
      - noto-fonts-cjk
      - ntp
      - oh-my-zsh-git
      - openssl
      - p7zip
      - pandoc
      - qemu
      - rsync
      - sysstat
      - transmission-gtk
      - ttf-google-fonts-git
      - unrar
      - unzip
      - viewnior
      - yaourt
      - zeal-git
      - zim

  - name: Install programming packages
    pacman: name={{ item }} state=latest
    with_items:
      - ack
      - boost
      - cargo
      - clang
      - cmake
      - cscope
      - emacs
      - flake8
      - global
      - go
      - go-tools
      - intellij-idea-community-edition
      - ipython
      - ipython2
      - jdk
      - llvm
      - pycharm-community
      - python-nose
      - python-pylint
      - python2-pylint
      - rust
      - the_silver_searcher
      - tig
      - yapf

  - name: Ensure basic services is running and enabled
    service: name={{ item }} state=started enabled=yes
    with_items:
      - fstrim.timer
      - ntpd

  - name: Disable sshd service
    service: name=sshd state=stopped enabled=no

  - name: Set jdk8 as default java
    shell: archlinux-java set java-8-jdk

  - name: Ensure sudoer user in /etc/sudoers
    lineinfile:
      regexp: '^{{ sudoer_user }} ALL=\(ALL\) NOPASSWD: ALL$'
      line: '{{ sudoer_user }} ALL=(ALL) NOPASSWD: ALL'
      dest: /etc/sudoers
      state: present
      backup: yes
      insertafter: EOF

  - sysctl: name="vm.swappiness" value=2 sysctl_set=yes state=present reload=yes
